# Generated by Django 6.0.6 on 2026-06-29 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(default='Ireland', max_length=50)),
                ('city', models.CharField(default='Dublin', max_length=60)),
                ('price', models.PositiveBigIntegerField()),
                ('number_of_room', models.PositiveBigIntegerField()),
                ('toilets', models.PositiveBigIntegerField()),
                ('description', models.TextField(max_length=200)),
                ('address', models.CharField(max_length=140)),
                ('pet_friendly', models.BooleanField(default=True)),
                ('room_kind', models.CharField(choices=[('double', 'Double room'), ('single', 'Single room'), ('shared', 'Shared room')], max_length=140)),
                ('amenity', models.ManyToManyField(to='rooms.amenity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
