# Generated by Django 6.0.6 on 2026-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
