# Generated by Django 6.0.6 on 2026-06-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perk',
            old_name='descrtiption',
            new_name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
    ]
