# Generated by Django 6.0.6 on 2026-06-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_rename_descrtiption_perk_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='perk',
            field=models.ManyToManyField(blank=True, null=True, to='experiences.perk'),
        ),
    ]
