# Generated by Django 6.0.6 on 2026-07-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('room', 'Room'), ('experience', 'Experience')], default='room', max_length=50),
            preserve_default=False,
        ),
    ]
