# Generated by Django 6.0.6 on 2026-06-30 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('experiences', '0003_alter_experience_perk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience',
        ),
        migrations.AddField(
            model_name='booking',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiences.experience'),
        ),
    ]
